import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navber from "../components/Navbar/Navbar";
import { getServerSession } from "next-auth";
import AuthSessionProvider from "@/utils/sessionProvider/sessionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider session={session}>
          <div>
            <Navber />
            <div className="mx-auto container px-4">{children}</div>
          </div>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
